{% set name = "pyftdi" %}
{% set version = "0.47.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c052daaca701459749d2c7261f64f3e695510677511fcc0ec31e1846af3b3832

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pyusb >=1.0.0
    - pyserial >=3.0

test:
  imports:
    - pyftdi.ftdi

about:
  home: https://github.com/eblot/pyftdi
  license: LGPL v2
  license_family: LGPL
  license_file: LICENSE.txt
  summary: FTDI device driver written in pure Python
  description: |
    PyFtdi aims at providing a user-space driver for modern FTDI devices,
    implemented in pure Python language.
  doc_url: http://eblot.github.io/pyftdi/
  dev_url: https://github.com/eblot/pyftdi

extra:
  recipe-maintainers:
    - abloemert
