travis:
  secure:
    BINSTAR_TOKEN: ce8B85gA6bRjQmloyKvjTIyPC0RkIL1nGYTZPUqOclDTUZhoRFsJOnVn8oUwHfkqe2fHxCx1502ZDuNzuR0F9Er4GmhAaKfLm8bEaRwZXC7gVkYYH6pVXVjVMQQ/DcwMDhCZLr/CkSaB4r+1jfaEdo+7aKB3+GZhg/bqCGTPWLQzP1EXWyY30XhDJYnc9lAIaPkkNPYoeB5bHADXFnuhcwffRzrhjIEey8fNqQIlX/dQRS/YbkQcFPrFTVm0obqA5MOItevQt9wlZAQxWILjbCu0PCGGs/c3ZQ96i0OeZKIwcsPsko4YubVeCvHczJEfHnGCh+VGmEFgGbWlX7UrcAZWN47pY0C/ybw16AfW4M5OuF7M5vH2PdQUFFnyxA0G8hTsasHKEjf9LhCWb4rf7rrCq1dv6wG00OsdUniNS5w61zJWzyDH7VJrq0Wik5Masr+798pK1AwJ4+C+il13B1KEw6K5W8JoHn8BypHGkWfCosqoQ+5QP7C4Ph8ieG4pCO/tJll+/pOFthbnAcQTaCX+V9+npKexhss89u0yKXbHvs2sYxyFYsd6eAi+hT+fL3PLeI5EKbDbeqbyB+1/T4noCKLDWo0G0AtJunoH0gHxvhFPPTX+Oew1foil3sQzmVMJVaSWSzWDXS8r/poN3vwrhzJr1r1uW02RJ0a23os=
conda_forge_output_validation: true
bot:
  automerge: true
